apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: weather-app-hpa
  namespace: weather-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-app
  minReplicas: 2  
  maxReplicas: 10 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Target CPU utilization (percentage)